openapi: 3.0.0
info:
  title: Bharath Resume
  description: Showcase workexperience in OAS format
  contact:
    name: Bharath
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
tags:
  - name: Basic Information
  - name: Skills
  - name: References
  - name: Publications
  - name: Languages
  - name: Interests
  - name: Education
  - name: Awards
  - name: Work
  - name: Volunteer
paths:
  '/user/{id}':
    get:
      tags:
        - Basic Information
      summary: Basic profile Information
      description: Basic profile Information
      operationId: getBasics
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
              examples:
                example-1:
                  value:
                    basics:
                      name: John Doe
                      label: Programmer
                      picture: ''
                      email: john@gmail.com
                      phone: (912) 555-4321
                      website: 'http://johndoe.com'
                      location:
                        address: 2712 Broadway St
                        postalCode: CA 94115
                        city: San Francisco
                        countryCode: US
                        region: California
                      profiles:
                        - network: Twitter
                          username: john
                          url: 'http://twitter.com/john'
      x-swagger-router-controller: BasicInformation
  '/user/{id}/work':
    get:
      tags:
        - Work
      summary: Your GET endpoint
      description: Get work experience details
      operationId: getWorkId
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_1'
                x-content-type: application/json
      x-swagger-router-controller: Work
  '/user/{id}/volunteer':
    get:
      tags:
        - Volunteer
      summary: Your GET endpoint
      description: Get voluteering experience details
      operationId: getVolunteerId
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_2'
                x-content-type: application/json
      x-swagger-router-controller: Volunteer
  '/user/{id}/education':
    get:
      tags:
        - Education
      summary: Your GET endpoint
      description: Get education details
      operationId: getEducationId
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Education'
                x-content-type: application/json
      x-swagger-router-controller: Education
  '/user/{id}/awards':
    get:
      tags:
        - Awards
      summary: Your GET endpoint
      description: Get awards details
      operationId: getAwardsId
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Awards'
                x-content-type: application/json
      x-swagger-router-controller: Awards
  '/user/{id}/publications':
    get:
      tags:
        - Publications
      summary: Your GET endpoint
      description: Get publication details
      operationId: getPublicationsId
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Publications'
                x-content-type: application/json
      x-swagger-router-controller: Publications
  '/user/{id}/skills':
    get:
      tags:
        - Skills
      summary: Your GET endpoint
      description: Get skill details
      operationId: getSkillsId
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Skills'
                x-content-type: application/json
      x-swagger-router-controller: Skills
    post:
      tags:
        - Skills
      summary: Skill POST endpoint
      description: Add skill details
      operationId: postSkillsId
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Skills'
      responses:
        '200':
          description: OK
      x-swagger-router-controller: Skills
  '/user/{id}/languages':
    get:
      tags:
        - Languages
      summary: Your GET endpoint
      description: Get language expertise details
      operationId: getLanaguagesId
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Languages'
                x-content-type: application/json
      x-swagger-router-controller: Languages
  '/user/{id}/interests':
    get:
      tags:
        - Interests
      summary: Your GET endpoint
      description: Get interests and hobby details
      operationId: getInterestsId
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Interests'
                x-content-type: application/json
      x-swagger-router-controller: Interests
    post:
      tags:
        - Interests
      summary: Interests POST endpoint
      description: Add interests and hobby details
      operationId: postUseIdInterests
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        description: Adding interests and hobby details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Interests'
      responses:
        '200':
          description: OK
      x-swagger-router-controller: Interests
  '/user/{id}/references':
    get:
      tags:
        - References
      summary: Your GET endpoint
      description: Get reference details
      operationId: getReferencesId
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/References'
                x-content-type: application/json
      x-swagger-router-controller: References
components:
  schemas:
    User:
      title: User
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        label:
          type: string
        picture:
          type: string
        email:
          type: string
        phone:
          type: string
        website:
          type: string
      example:
        website: website
        phone: phone
        name: name
        id: id
        label: label
        picture: picture
        email: email
    Location:
      title: Location
      required:
        - countryCode
        - id
      type: object
      properties:
        id:
          type: string
        address:
          type: string
        postcalCode:
          type: number
        city:
          type: string
        countryCode:
          type: string
        region:
          type: string
      example:
        address: address
        city: city
        postcalCode: 0.8008281904610115
        countryCode: countryCode
        id: id
        region: region
    Profiles:
      title: Profiles
      required:
        - id
      type: object
      properties:
        id:
          type: string
        network:
          type: string
        username:
          type: string
        url:
          type: string
      example:
        id: id
        url: url
        network: network
        username: username
    Role:
      title: Role
      type: object
      properties:
        id:
          type: string
        position:
          type: string
        website:
          type: string
        startDate:
          type: string
        endDate:
          type: string
        summary:
          type: string
        highlights:
          type: array
          items:
            type: string
      example:
        summary: summary
        website: website
        highlights:
          - highlights
          - highlights
        endDate: endDate
        id: id
        position: position
        startDate: startDate
    Education:
      title: Education
      required:
        - id
        - institute
      type: object
      properties:
        id:
          type: string
        institute:
          type: string
        area:
          type: string
        studyType:
          type: string
        startDate:
          type: string
        endDate:
          type: string
        gpa:
          type: string
        courses:
          type: array
          items:
            type: string
      example:
        area: area
        courses:
          - courses
          - courses
        endDate: endDate
        studyType: studyType
        gpa: gpa
        institute: institute
        id: id
        startDate: startDate
    Awards:
      title: Awards
      required:
        - id
        - title
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        date:
          type: string
        awarder:
          type: string
        summary:
          type: string
      example:
        date: date
        summary: summary
        awarder: awarder
        id: id
        title: title
    Publications:
      title: Publication
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        publisher:
          type: string
        releaseDate:
          type: string
        website:
          type: string
        summary:
          type: string
      example:
        summary: summary
        website: website
        releaseDate: releaseDate
        name: name
        publisher: publisher
        id: id
    Skills:
      title: Skills
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        level:
          type: string
        keywords:
          type: array
          items:
            type: string
      example:
        keywords:
          - keywords
          - keywords
        level: level
        name: name
        id: id
    Languages:
      title: Languages
      type: object
      properties:
        id:
          type: string
        language:
          type: string
        fluency:
          type: string
      example:
        fluency: fluency
        language: language
        id: id
    Interests:
      title: Interests
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        keywords:
          type: array
          items:
            type: string
      example:
        keywords:
          - keywords
          - keywords
        name: name
        id: id
    References:
      title: References
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        reference:
          type: string
      example:
        reference: reference
        name: name
        id: id
    inline_response_200:
      type: object
      properties:
        basics:
          $ref: '#/components/schemas/User'
        location:
          $ref: '#/components/schemas/Location'
        profiles:
          type: array
          items:
            $ref: '#/components/schemas/Profiles'
      example:
        basics:
          website: website
          phone: phone
          name: name
          id: id
          label: label
          picture: picture
          email: email
        profiles:
          - id: id
            url: url
            network: network
            username: username
          - id: id
            url: url
            network: network
            username: username
        location:
          address: address
          city: city
          postcalCode: 0.8008281904610115
          countryCode: countryCode
          id: id
          region: region
    inline_response_200_1:
      type: object
      properties:
        company:
          type: string
        role:
          $ref: '#/components/schemas/Role'
      example:
        role:
          summary: summary
          website: website
          highlights:
            - highlights
            - highlights
          endDate: endDate
          id: id
          position: position
          startDate: startDate
        company: company
    inline_response_200_2:
      type: object
      properties:
        organization:
          type: string
        role:
          $ref: '#/components/schemas/Role'
      example:
        role:
          summary: summary
          website: website
          highlights:
            - highlights
            - highlights
          endDate: endDate
          id: id
          position: position
          startDate: startDate
        organization: organization
